[package]
name = "bar"
version = "0.1.0"
edition = "2024"
authors = ["piyush"]

[dependencies]
clap = "2.27.1" # from crates.io
rand = { git = "https://github.com/rust-lang-nursery/rand" } # from online repo
bar = { path = "../bar" } # from a path in the local filesystem
